<div alt="Special" aria-label="Special" class="bb-button-icon" data-dropdown="true" rel="special">
	<span class="bb-icon-special"></span>
	<div id="bb-specialchars" data-rule="specialchars" class="bb-dropdown open" style="display: none;position: absolute;">
	<div class="bb-dropdown-cells">
		<a href="javascript:void(0)" rel="lsquo" data-rule="special">&lsquo;</a>
		<a href="javascript:void(0)" rel="rsquo" data-rule="special">&rsquo;</a>
		<a href="javascript:void(0)" rel="ldquo" data-rule="special">&ldquo;</a>
		<a href="javascript:void(0)" rel="rdquo" data-rule="special">&rdquo;</a>
		<a href="javascript:void(0)" rel="ndash" data-rule="special">&ndash;</a>
		<a href="javascript:void(0)" rel="mdash" data-rule="special">&mdash;</a>
		<a href="javascript:void(0)" rel="divide" data-rule="special">&divide;</a>
		<a href="javascript:void(0)" rel="hellip" data-rule="special">&hellip;</a>
		<a href="javascript:void(0)" rel="trade" data-rule="special">&trade;</a>
		<a href="javascript:void(0)" rel="bull" data-rule="special">&bull;</a>
		<a href="javascript:void(0)" rel="rarr" data-rule="special">&rarr;</a>
		<a href="javascript:void(0)" rel="asymp" data-rule="special">&asymp;</a>
		<a href="javascript:void(0)" rel="$" data-rule="special">$</a>
		<a href="javascript:void(0)" rel="euro" data-rule="special">&euro;</a>
		<a href="javascript:void(0)" rel="cent" data-rule="special">&cent;</a>
		<a href="javascript:void(0)" rel="pound" data-rule="special">&pound;</a>
		<a href="javascript:void(0)" rel="yen" data-rule="special">&yen;</a>
		<a href="javascript:void(0)" rel="iexcl" data-rule="special">&iexcl;</a>
		<a href="javascript:void(0)" rel="curren" data-rule="special">&curren;</a>
		<a href="javascript:void(0)" rel="brvbar" data-rule="special">&brvbar;</a>
		<a href="javascript:void(0)" rel="sect" data-rule="special">&sect;</a>
		<a href="javascript:void(0)" rel="uml" data-rule="special">&uml;</a>
		<a href="javascript:void(0)" rel="copy" data-rule="special">&copy;</a>
		<a href="javascript:void(0)" rel="ordf" data-rule="special">&ordf;</a>
		<a href="javascript:void(0)" rel="laquo" data-rule="special">&laquo;</a>
		<a href="javascript:void(0)" rel="raquo" data-rule="special">&raquo;</a>
		<a href="javascript:void(0)" rel="not" data-rule="special">&not;</a>
		<a href="javascript:void(0)" rel="reg" data-rule="special">&reg;</a>
		<a href="javascript:void(0)" rel="macr" data-rule="special">&macr;</a>
		<a href="javascript:void(0)" rel="deg" data-rule="special">&deg;</a>
		<a href="javascript:void(0)" rel="sup1" data-rule="special">&sup1;</a>
		<a href="javascript:void(0)" rel="sup2" data-rule="special">&sup2;</a>
		<a href="javascript:void(0)" rel="sup3" data-rule="special">&sup3;</a>
		<a href="javascript:void(0)" rel="acute" data-rule="special">&acute;</a>
		<a href="javascript:void(0)" rel="micro" data-rule="special">&micro;</a>
		<a href="javascript:void(0)" rel="para" data-rule="special">&para;</a>
		<a href="javascript:void(0)" rel="middot" data-rule="special">&middotl</a>
		<a href="javascript:void(0)" rel="cedil" data-rule="special">&cedil;</a>
		<a href="javascript:void(0)" rel="ordm" data-rule="special">&ordm;</a>
		<a href="javascript:void(0)" rel="frac14" data-rule="special">&frac14;</a>
		<a href="javascript:void(0)" rel="frac12" data-rule="special">&frac12;</a>
		<a href="javascript:void(0)" rel="frac34" data-rule="special">&frac34;</a>
		<a href="javascript:void(0)" rel="iquest" data-rule="special">&iquest;</a>
		<a href="javascript:void(0)" rel="Agrave" data-rule="special">&Agrave;</a>
		<a href="javascript:void(0)" rel="Aacute" data-rule="special">&Aacute;</a>
		<a href="javascript:void(0)" rel="Acirc" data-rule="special">&Acirc;</a>
		<a href="javascript:void(0)" rel="Atilde" data-rule="special">&Atilde;</a>
		<a href="javascript:void(0)" rel="Auml" data-rule="special">&Auml;</a>
		<a href="javascript:void(0)" rel="Aring" data-rule="special">&Aring;</a>
		<a href="javascript:void(0)" rel="AElig" data-rule="special">&AElig;</a>
		<a href="javascript:void(0)" rel="Ccedil" data-rule="special">&Ccedil;</a>
		<a href="javascript:void(0)" rel="Egrave" data-rule="special">&Egrave;</a>
		<a href="javascript:void(0)" rel="Eacute" data-rule="special">&Eacute;</a>
		<a href="javascript:void(0)" rel="Ecirc" data-rule="special">&Ecirc;</a>
		<a href="javascript:void(0)" rel="Euml" data-rule="special">&Euml;</a>
		<a href="javascript:void(0)" rel="Igrave" data-rule="special">&Igrave;</a>
		<a href="javascript:void(0)" rel="Iacute" data-rule="special">&Iacute;</a>
		<a href="javascript:void(0)" rel="Icirc" data-rule="special">&Icirc;</a>
		<a href="javascript:void(0)" rel="Iuml" data-rule="special">&Iuml;</a>
		<a href="javascript:void(0)" rel="ETH" data-rule="special">&ETH;</a>
		<a href="javascript:void(0)" rel="Ntilde" data-rule="special">&Ntilde;</a>
		<a href="javascript:void(0)" rel="Ograve" data-rule="special">&Ograve;</a>
		<a href="javascript:void(0)" rel="Oacute" data-rule="special">&Oacute;</a>
		<a href="javascript:void(0)" rel="Ocirc" data-rule="special">&Ocirc;</a>
		<a href="javascript:void(0)" rel="Otilde" data-rule="special">&Otilde;</a>
		<a href="javascript:void(0)" rel="Ouml" data-rule="special">&Ouml;</a>
		<a href="javascript:void(0)" rel="times" data-rule="special">&times;</a>
		<a href="javascript:void(0)" rel="Oslash" data-rule="special">&Oslash;</a>
		<a href="javascript:void(0)" rel="Ugrave" data-rule="special">&Ugrave;</a>
		<a href="javascript:void(0)" rel="Uacute" data-rule="special">&Uacute;</a>
		<a href="javascript:void(0)" rel="Ucirc" data-rule="special">&Ucirc;</a>
		<a href="javascript:void(0)" rel="Uuml" data-rule="special">&Uuml;</a>
		<a href="javascript:void(0)" rel="Yacute" data-rule="special">&Yacute;</a>
		<a href="javascript:void(0)" rel="THORN" data-rule="special">&THORN;</a>
		<a href="javascript:void(0)" rel="szlig" data-rule="special">&szlig;</a>
		<a href="javascript:void(0)" rel="agrave" data-rule="special">&agrave;</a>
		<a href="javascript:void(0)" rel="aacute" data-rule="special">&aacute;</a>
		<a href="javascript:void(0)" rel="acirc" data-rule="special">&acirc;</a>
		<a href="javascript:void(0)" rel="atilde" data-rule="special">&atilde;</a>
		<a href="javascript:void(0)" rel="auml" data-rule="special">&auml;</a>
		<a href="javascript:void(0)" rel="aring" data-rule="special">&aring;</a>
		<a href="javascript:void(0)" rel="aelig" data-rule="special">&aelig;</a>
		<a href="javascript:void(0)" rel="ccedil" data-rule="special">&ccedil;</a>
		<a href="javascript:void(0)" rel="egrave" data-rule="special">&egrave;</a>
		<a href="javascript:void(0)" rel="eacute" data-rule="special">&eacute;</a>
		<a href="javascript:void(0)" rel="ecirc" data-rule="special">&ecirc;</a>
		<a href="javascript:void(0)" rel="euml" data-rule="special">&euml;</a>
		<a href="javascript:void(0)" rel="igrave" data-rule="special">&igrave;</a>
		<a href="javascript:void(0)" rel="iacute" data-rule="special">&iacute;</a>
		<a href="javascript:void(0)" rel="icirc" data-rule="special">&icirc;</a>
		<a href="javascript:void(0)" rel="iuml" data-rule="special">&iuml;</a>
		<a href="javascript:void(0)" rel="eth" data-rule="special">&eth;</a>
		<a href="javascript:void(0)" rel="ntilde" data-rule="special">&ntilde;</a>
		<a href="javascript:void(0)" rel="ograve" data-rule="special">&ograve;</a>
		<a href="javascript:void(0)" rel="oacute" data-rule="special">&oacute;</a>
		<a href="javascript:void(0)" rel="ocirc" data-rule="special">&ocirc;</a>
		<a href="javascript:void(0)" rel="otilde" data-rule="special">&otilde;</a>
		<a href="javascript:void(0)" rel="ouml" data-rule="special">&ouml;</a>
		<a href="javascript:void(0)" rel="oslash" data-rule="special">&oslash;</a>
		<a href="javascript:void(0)" rel="ugrave" data-rule="special">&ugrave;</a>
		<a href="javascript:void(0)" rel="uacute" data-rule="special">&uacute;</a>
		<a href="javascript:void(0)" rel="ucirc" data-rule="special">&ucirc;</a>
		<a href="javascript:void(0)" rel="uuml" data-rule="special">&uuml;</a>
		<a href="javascript:void(0)" rel="yacute" data-rule="special">&yacute;</a>
		<a href="javascript:void(0)" rel="thorn" data-rule="special">&yuml;</a>
		<a href="javascript:void(0)" rel="yuml" data-rule="special">&#375;</a>
		<a href="javascript:void(0)" rel="OElig" data-rule="special">&OElig;</a>
		<a href="javascript:void(0)" rel="oelig" data-rule="special">&oelig;</a>
		<a href="javascript:void(0)" rel="#372" data-rule="special">&#374;</a>
		<a href="javascript:void(0)" rel="#374" data-rule="special">&#375;</a>
		<a href="javascript:void(0)" rel="#373" data-rule="special">&#373;</a>
		<a href="javascript:void(0)" rel="#375" data-rule="special">&#375;</a>
	</div>
</div>
</div>